app/campaigns/models.py
from app import db
from flask import current_app
from flask_login import current_user
from sqlalchemy import TEXT, Column, Boolean, ForeignKey, TEXT, INTEGER, VARCHAR
import jwt
from datetime import datetime, timezone, timedelta


class AmbassadorMap(db.Model):
    __tablename__ = 'ambassador_map'
    id            = Column('id', INTEGER(), primary_key=True)
    campaign_id   = Column('campaign_id', INTEGER(), nullable=False)
    user_id       = Column('user_id', INTEGER(), nullable=False)
    goal          = Column('ambassador_goal', INTEGER())



class Campaign(db.Model):
    __tablename__ = 'campaign'
    id            = Column('id', INTEGER(), primary_key=True)
    title         = Column('title', TEXT(), nullable=False)
    active        = Column('active', Boolean(), nullable=False, default=True)
    goal          = Column('goal', INTEGER(), default=0)
    archived      = Column('archived', Boolean(), default=False)

    def get_donations(self):
        from app.main.models import Donation
        return Donation.query.filter_by(campaign_id=self.id).all()
    
    def get_amount_raised(self):
        donations = self.get_donations()
        total = 0
        for donation in donations:
            total += donation.amount
        return total
    
    def get_ambassadors(self):
        return AmbassadorMap.query.filter_by(campaign_id=self.id).all()


    def __repr__(self) -> str:
        return f"{self.id} - {self.title}"

app/campaigns/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, \
                    EmailField, \
                    PasswordField, \
                    SubmitField, \
                    SelectField, \
                    BooleanField,\
                    DateField, IntegerField
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms.validators import DataRequired, ValidationError, NumberRange, EqualTo, Email
from app.campaigns.models import Campaign
from flask_login import current_user
# import logging
# logging.basicConfig(filename='logs.log', encoding='utf-8', level=logging.DEBUG)

class CreateCampaignForm(FlaskForm):
    title        = StringField('Title', validators=[DataRequired()])
    active       = BooleanField('Initialize as active?')
    goal         = IntegerField('Goal')
    submit       = SubmitField('Add Campaign')

app/campaigns/__init__.py
from flask import Blueprint

campaigns = Blueprint('campaigns', 
                     __name__, 
                     template_folder='templates', 
                     static_folder='static',
                     url_prefix='/campaigns')

from app.campaigns import routes

app/campaigns/campaign_api/__init__.py
from flask import Blueprint

campaign_api = Blueprint('campaign_api', 
                     __name__, 
                     template_folder='templates', 
                     static_folder='static',
                     url_prefix='/campaign_api')

from app.campaigns.campaign_api import routes

app/campaigns/campaign_api/routes.py
from app import db
from flask import render_template
from app.campaigns.campaign_api import campaign_api
from app.campaigns.models import Campaign
from time import sleep



@campaign_api.route('update_active_status/<id>/<status>', methods=['PUT'])
def update_active_status(id, status):
    if status == 'true':
        status = True
    else:
        status = False
    Campaign.query.filter_by(id=id).update({'active':status})
    db.session.commit()
    sleep(1)
    return {'status':'success'}

@campaign_api.route('archive_campaign/<id>', methods=['PUT'])
def archive_campaign(id):
    Campaign.query.filter_by(id=id).update({'archived': True, 'active':False})
    db.session.commit()
    return {'status':'success'}

@campaign_api.route('un_archive_campaign/<id>', methods=['PUT'])
def un_archive_campaign(id):
    Campaign.query.filter_by(id=id).update({'archived': False, 'active':False})
    db.session.commit()
    return {'status':'success'}

app/campaigns/routes.py
from app import db
from app.campaigns import campaigns
from app.users.models import User
from app.campaigns.models import Campaign
from app.campaigns.forms import CreateCampaignForm
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, login_user, current_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash
from datetime import datetime
import os
from time import sleep

@campaigns.route('add_campaign', methods=['GET', 'POST'])
def add_campaign():
    form = CreateCampaignForm()
    if form.validate_on_submit():
        campaign = Campaign(
            title=form.title.data,
            active=form.active.data,
            goal=form.goal.data
        )
        db.session.add(campaign)
        db.session.commit()
        return redirect(url_for('admin.administration'))
    return render_template('add_campaign.html',
                           form=form)

@campaigns.route('campaign_page/<campaign_id>')
def campaign_page(campaign_id):
    campaign = Campaign.query.filter_by(id=campaign_id).first()
    return render_template('campaign_page.html',
                           campaign=campaign)

@campaigns.route('add_ambassador')
def add_ambassador():
    return render_template('add_ambassador.html')

app/campaigns/templates/add_campaign.html
{% extends 'base.html' %}
{% block title %}Add campaign{% endblock title %}
{% block content %}
<main class="container-lg mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Register</h3>
                    <form method="post" enctype="multipart/form-data">
                        {{ form.hidden_tag() }}

                        <div class="mb-3">
                            {{ form.title.label(class="form-label") }}
                            {{ form.title(class="form-control") }}
                            {% if form.title.errors %}
                                <ul class="errors">
                                    {% for error in form.title.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>

                        <div class="mb-3">
                            {{ form.active.label(class="form-label") }}
                            {{ form.active() }}
                            {% if form.active.errors %}
                                <ul class="errors">
                                    {% for error in form.active.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        
                        <div class="mb-3">
                            {{ form.goal.label(class="form-label") }}
                            {{ form.goal(class="form-control") }}
                            {% if form.goal.errors %}
                                <ul class="errors">
                                    {% for error in form.goal.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                        
                        {{ form.submit(class='btn btn-primary') }}
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

app/campaigns/templates/campaign_page.html
{% extends 'base.html' %}
{% block title %}{{campaign.title}}{% endblock title %}
{% block content %}
<main class="container-lg mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mb-5">
                <div class="card-body">
                    <div class="d-flex justify-content-center align-items-center">
                        <h2 class="text-center">{{campaign.title}} Ambassadors</h2>
                        <a href="{{url_for('campaigns.add_ambassador')}}" class="btn btn-primary">Become an ambassador!</a>
                    </div>
                    <table class="table table-bordered table-striped">
                        <thead class="table-dark">
                            <tr>
                                <th>Name</th>
                                <th>Goal</th>
                                <th>Ambassador Page Link</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for campaign_ambassador in campaign.get_ambassadors() %}
                            <tr>
                                <td>{{campaign_ambassador.user_id}}</td>
                                <td>{{campaign_ambassador.goal}}</td>
                                <td></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h2 class="text-center">{{campaign.title}}</h2>
                    
                    <table class="table table-bordered table-striped">
                        <thead class="table-dark">
                            <tr>
                                <th>#</th>
                                <th>Amount</th>
                                <th>User</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for campaign_donation in campaign.get_donations() %}
                            <tr>
                                <td>{{campaign_donation.id}}</td>
                                <td>{{campaign_donation.amount}}</td>
                                <td>{{campaign_donation.get_user()}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}