app/main/models.py
from app import db
from flask import current_app
from flask_login import UserMixin, current_user
from sqlalchemy import TEXT, Column, Boolean, ForeignKey, TEXT, INTEGER, VARCHAR
import jwt
from datetime import datetime, timezone, timedelta


class Donation(db.Model):
    __tablename__ = 'donation'
    id            = Column('id', INTEGER(), primary_key=True, autoincrement=True)
    currency_type = Column('currency_type', TEXT(), nullable=False)
    amount        = Column('amount', INTEGER(), nullable=False)
    user_id       = Column('user_id', INTEGER(), nullable=False)
    campaign_id   = Column('campaign_id', INTEGER(), nullable=False)
    anonymous     = Column('anonymous', Boolean(), default=False)
    
    def get_user(self):
        from app.users.models import User
        return User.query.filter_by(id=self.user_id).first()

    def __repr__(self) -> str:
        return f"{self.id} - {self.currency_type} - {self.amount}"

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', 
                     __name__, 
                     template_folder='templates', 
                     static_folder='static',
                     url_prefix='/main')

from app.main import routes

app/main/routes.py
from app import db
from app.main import main
from app.users.models import User
from app.campaigns.models import Campaign
# from forms import LoginForm, RequestResetForm, ResetPasswordForm, EditUserForm, AddUserForm
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, login_user, current_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash
from datetime import datetime
import os
# import logging
# logging.basicConfig(filename='logs.log', encoding='utf-8', level=logging.INFO)


@main.route('/homepage')
def homepage():
    active_campaigns = Campaign.query.filter_by(active=True).all()
    return render_template('homepage.html',
                           active_campaigns=active_campaigns)

app/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('main.static', filename='main.css') }}">
    {% block stylesheet %}{% endblock stylesheet %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="{{url_for('main.homepage')}}" style="text-decoration: none; margin-right: 10px;"><p>Pilzno</p></a>
        {% if current_user.is_authenticated %}
            <a href="{{url_for('users.user_page', user_id=current_user.id)}}" style="text-decoration: none;"><span class="navbar-brand">User Page</span></a>
            {% if current_user.user_type == 'Admin' %}
                <a href="{{url_for('admin.administration')}}" style="text-decoration: none;"><span class="navbar-brand">Admin Management</span></a>
                <a href="{{url_for('admin.archive')}}" style="text-decoration: none;"><span class="navbar-brand">Archive</span></a>
            {% endif %}
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="{{url_for('users.logout')}}">Logout</a>
            </div>
            </div>
        {% else %}
            <a href="{{url_for('users.login')}}" style="text-decoration: none;"><span class="navbar-brand">Login</span></a>
            <a href="{{url_for('users.register_user')}}" style="text-decoration: none;"><span class="navbar-brand">Register</span></a>
        {% endif %}
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block content %}{% endblock content %}
</body>
</html>

app/main/templates/homepage.html
{% extends 'base.html' %}
{% block title %}Homepage{% endblock title %}

{% block stylesheet %}
<style>
    .custom-table {
        border-radius: 15px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        overflow: hidden; /* Ensures rounded corners apply to the entire table */
    }
</style>
{% endblock stylesheet %}
{% block content %}
<main>
    <div class="container my-4 px-5">
        <div class="text-center mb-4">
            <a href="{{ url_for('arba_yesodot.arba_yesodot_homepage') }}" class="btn btn-primary">Check out the arba yesodot program!</a>
        </div>
        <h2 class="text-center">Visit Campaigns</h2>
        
        <table class="table table-bordered table-striped custom-table">
            <thead class="table-dark">
                <tr>
                    <th>Title</th>
                    <th>Goal</th>
                    <th>Raised</th>
                    <th>Campaign Link</th>
                </tr>
            </thead>
            <tbody>
                {% for campaign in active_campaigns %}
                    <tr>
                        <td>{{campaign.title}}</td>
                        <td>{{campaign.goal}}</td>
                        <td>{{campaign.get_amount_raised()}}</td>
                        <td><a href="{{url_for('campaigns.campaign_page', campaign_id=campaign.id)}}">See campaign details</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
</main>
{% endblock content %}